services:
  - type: web
    name: face-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn face_api:app
    plan: free
    autoDeploy: true
    envVars:
      - key: GOOGLE_APPLICATION_CREDENTIALS
        value: serviceAccountKey.json
